version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newTestApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jfljmte9flbb"
s3_prefix = "newTestApp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
